//program to implement collatz conjecture


//The Syracuse (also called the Collatz or Hailstone) sequence is generated by starting
//with a natural number
//and repeatedly applying the following function until it returns 1.
//syr(x)= x/2 if x is even else 3x+1

//It is an open question in maths whether this sequence will always end up at 1 for every
// possible starting value.
//Write a program that gets a starting value from the user and prints its Syracuse sequence
#include <iostream>
#include <conio.h>
void collatz_theorem(int);
main(){
	int number(90);
	std::cout<<"Enter a number to try collatz conjecture:"<<std::endl;
	std::cin>>number;//tried with 5, 9
	collatz_theorem(number);
	getch();
}

void collatz_theorem(int x){
	int y=x;
	while(y!=1){
		std::cout<<y<<"->";
		y = y%2? 3*y+1 : y /=2;
	}
	std::cout<<y;//now that y is one end
}
